mail:
    host: smtp.163.com
    username: xiao21wei2022@163.com           #邮箱的发件人
    password: XRECLTVGMJSQGUUA                #邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
