# Generated by Django 4.1.3 on 2022-11-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="my_app",
            fields=[
                ("achievement_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("author_id", models.CharField(max_length=256)),
                ("intro", models.CharField(max_length=256)),
                ("url", models.CharField(max_length=256)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("type", models.IntegerField()),
                ("area", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name": "my_app",
                "verbose_name_plural": "achievements",
                "db_table": "my_app",
                "ordering": ["achievement_id"],
            },
        ),
        migrations.CreateModel(
            name="admin",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("password", models.CharField(max_length=256)),
                ("email", models.CharField(max_length=256, unique=True)),
            ],
            options={
                "verbose_name": "admin",
                "verbose_name_plural": "admins",
                "db_table": "admin",
                "ordering": ["admin_id"],
            },
        ),
        migrations.CreateModel(
            name="chat",
            fields=[
                ("chat_id", models.AutoField(primary_key=True, serialize=False)),
                ("send", models.IntegerField()),
                ("receive", models.IntegerField()),
                ("content", models.CharField(max_length=256)),
                ("send_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "chat",
                "verbose_name_plural": "chats",
                "db_table": "chat",
                "ordering": ["chat_id"],
            },
        ),
        migrations.CreateModel(
            name="collection",
            fields=[
                ("collection_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("achievement_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "collection",
                "verbose_name_plural": "collections",
                "db_table": "collection",
                "ordering": ["collection_id"],
            },
        ),
        migrations.CreateModel(
            name="comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("achievement_id", models.IntegerField()),
                ("content", models.CharField(max_length=256)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "db_table": "comment",
                "ordering": ["comment_id"],
            },
        ),
        migrations.CreateModel(
            name="follow",
            fields=[
                ("follow_id", models.AutoField(primary_key=True, serialize=False)),
                ("user1_id", models.IntegerField()),
                ("user2_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "follow",
                "verbose_name_plural": "follows",
                "db_table": "follow",
                "ordering": ["follow_id"],
            },
        ),
        migrations.CreateModel(
            name="like",
            fields=[
                ("like_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("achievement_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "like",
                "verbose_name_plural": "likes",
                "db_table": "like",
                "ordering": ["like_id"],
            },
        ),
        migrations.CreateModel(
            name="report",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("send", models.IntegerField()),
                ("achievement_id", models.IntegerField()),
                ("content", models.CharField(max_length=256)),
                ("admin", models.IntegerField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("result", models.IntegerField()),
            ],
            options={
                "verbose_name": "report",
                "verbose_name_plural": "reports",
                "db_table": "report",
                "ordering": ["report_id"],
            },
        ),
        migrations.CreateModel(
            name="team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("intro", models.CharField(max_length=256)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("user_list", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name": "team",
                "verbose_name_plural": "teams",
                "db_table": "team",
                "ordering": ["team_id"],
            },
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("password", models.CharField(max_length=256)),
                ("email", models.CharField(max_length=256, unique=True)),
                ("address", models.CharField(max_length=256)),
                ("identity", models.IntegerField()),
                ("intro", models.CharField(max_length=256)),
                ("penalty", models.BooleanField(default=False)),
                ("birthday", models.DateField()),
                ("team_id", models.IntegerField()),
                ("real_name", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "user",
                "ordering": ["user_id"],
            },
        ),
    ]
