# Generated by Django 4.1.3 on 2022-12-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("achievement_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("author_id", models.CharField(max_length=256)),
                ("intro", models.CharField(default="未填写", max_length=256)),
                ("url", models.CharField(default="未填写", max_length=256)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("type", models.IntegerField(default=0)),
                ("area", models.CharField(default="未填写", max_length=256)),
            ],
            options={
                "verbose_name": "achievement",
                "verbose_name_plural": "achievements",
                "db_table": "achievement",
                "ordering": ["achievement_id"],
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("password", models.CharField(max_length=256)),
                ("email", models.CharField(max_length=256, unique=True)),
            ],
            options={
                "verbose_name": "admin",
                "verbose_name_plural": "admins",
                "db_table": "admin",
                "ordering": ["admin_id"],
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("chat_id", models.AutoField(primary_key=True, serialize=False)),
                ("send", models.IntegerField()),
                ("receive", models.IntegerField()),
                ("content", models.CharField(max_length=256)),
                ("send_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "chat",
                "verbose_name_plural": "chats",
                "db_table": "chat",
                "ordering": ["chat_id"],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("collection_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("achievement_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "collection",
                "verbose_name_plural": "collections",
                "db_table": "collection",
                "ordering": ["collection_id"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("achievement_id", models.IntegerField()),
                ("content", models.CharField(max_length=256)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "db_table": "comment",
                "ordering": ["comment_id"],
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                ("follow_id", models.AutoField(primary_key=True, serialize=False)),
                ("user1_id", models.IntegerField()),
                ("user2_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "follow",
                "verbose_name_plural": "follows",
                "db_table": "follow",
                "ordering": ["follow_id"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("like_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("achievement_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "like",
                "verbose_name_plural": "likes",
                "db_table": "like",
                "ordering": ["like_id"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("send", models.IntegerField()),
                ("achievement_id", models.IntegerField()),
                ("content", models.CharField(max_length=256)),
                ("admin", models.IntegerField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("result", models.IntegerField()),
            ],
            options={
                "verbose_name": "report",
                "verbose_name_plural": "reports",
                "db_table": "report",
                "ordering": ["report_id"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("intro", models.CharField(default="未填写", max_length=256)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("user_list", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name": "team",
                "verbose_name_plural": "teams",
                "db_table": "team",
                "ordering": ["team_id"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=256)),
                ("password", models.CharField(max_length=256)),
                ("email", models.CharField(max_length=256, unique=True)),
                ("address", models.CharField(default="未填写", max_length=256)),
                ("identity", models.IntegerField(default=0)),
                ("intro", models.CharField(default="未填写", max_length=256)),
                ("penalty", models.BooleanField(default=False)),
                ("birthday", models.DateField(auto_now_add=True, null=True)),
                ("team_id", models.IntegerField(null=True)),
                ("real_name", models.CharField(default="未填写", max_length=256)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "user",
                "ordering": ["user_id"],
            },
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                ("code_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=256)),
                ("code", models.CharField(max_length=256)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "verification_code",
                "verbose_name_plural": "verification_codes",
                "db_table": "verification_code",
                "ordering": ["code_id"],
            },
        ),
    ]
