# Generated by Django 4.1.3 on 2022-12-06 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_verificationcode"),
    ]

    operations = [
        migrations.RenameModel(old_name="my_app", new_name="Achievement",),
    ]
